var adminDashController = require('../controllers/dasboards/admindashboardcontroller')


module.exports=function(app){
    app.route('/api/admin/allcustomers')
    .get(adminDashController.allCustomers)
    app.route('/api/admin/allsellers')
    .get(adminDashController.allSellers)
    app.route('/api/admin/allshippingvendors')
    .get(adminDashController.allShippingvendors)
    app.route('/api/admin/role')
    .get(adminDashController.roleByEmail)
    app.route('/api/admin/userinfo')
    .get(adminDashController.infoByEmail)
    app.route('/api/admin/minpriceproduct')
    .get(adminDashController.minPriceProduct)
    app.route('/api/admin/maxpriceproduct')
    .get(adminDashController.maxPriceProduct)
    app.route('/api/admin/topproduct')
    .get(adminDashController.topTenproduct)
    app.route('/api/admin/topcustomer')
    .get(adminDashController.topTenCustomers)
    app.route('/api/admin/topseller')
    .get(adminDashController.topTenSellers)
    app.route('/api/admin/topshipper')
    .get(adminDashController.topTenShippingvendors)
    app.route('/api/admin/sameadresscustomer')
    .get(adminDashController.topTenproduct)
}
